### ISSUE TITLE
Running from command line

### ISSUE THREAD

**Issue by alpha-beta-soup** [christiankaiser/ScapeToad#3]
I notice that in [`ScapeToad.java`](https://github.com/christiankaiser/ScapeToad/blob/master/src/src/ScapeToad.java) there is a hint for running ScapeToad from the CLI: https://github.com/christiankaiser/ScapeToad/blob/master/src/src/ScapeToad.java#L49

However the code for parsing the command line arguments a few lines down has been commented out. I have very limited experience with Java, and I'm just wondering if it's still possible to run ScapeToad as a CLI tool?

**Comment by christiankaiser** [comment]
There was some attempts in making ScapeToad accessible from the CLI. However, this step has never been really completed.

We are currently rewriting ScapeToad and will then have a Python library for making cartograms. But this is not yet ready.

In the meantime, you can check out the [spatial-tools repo](https://github.com/christiankaiser/spatial-tools). This is basically a collection of CLI programs written in C, and some of them are about creating cartograms, based on the work of Mark Newman and Michael Gastner who did develop the cartogram algorithm that is used in ScapeToad. I did write these tools some years ago, but I think it should still work. There are a series of programs needed for making a cartogram. All the programs starting with r.morph.* are about map morphing (and hence cartograms too). These programs work with raster files instead of vector files. But there is a program to convert vector to raster. So a typical workflow could be:

- v.to.raster to convert Shapefiles to a Raster file
- r.morph.create.grid to create a deformation grid (e.g. 512x512 shape, or more depending on the quality of the cartogram you want)
- r.morph.equalize.density to make the cartogram computation (a cartogram is techniqually a density equalizing algorithm, and the density should be the same everywhere in the perfect cartogram)
- r.morph.transform for applying the calculated cartogram transformation to any layer you want

Hope this helps!

**Comment by alpha-beta-soup** [comment]
Thanks, that's very helpful.
